### ISSUE TITLE
Prevent YouTube iFrame API from loading multiple times

### ISSUE THREAD

**Issue by lmartins** [Blocklevel/vue-media-embed#4]
I've noticed that on a page with multiple YouTube embeds, the page will make multiple networks requests, which are multiplied by the number of videos present.

Any way to prevent this behaviour, either by listen to the API events or by delaying the plugin initialisation depending on a parent component state?

**Comment by supr3m0** [comment]
you are right, 
i am working on a new release atm and will fix this issue as well. thx for reporting

**Comment by lmartins** [comment]
Awesome. Thanks @supr3m0. Let me know if you want me to help testing the new version.

**Comment by supr3m0** [comment]
hiya ! a just released a new version (v1.0.0), please let me know if you find any problems. I changed the build process so hopefully this won't cause any issues...

**Comment by lmartins** [comment]
Hi @supr3m0,

I've pushed a new build using the latest version. On the build process apparently nothing was broken with the updates, on the other hand im still seeing multiple requests for the same assets:
https://cl.ly/233x231D463K

If you want to see it happening on a browser, you can check this address: http://grubstick.myshopify.com/?preview_theme_id=170627405

**Comment by supr3m0** [comment]
hiya @lmartins thx for testing the latest version
i changed the loading of the youtube iframe script  (//www.youtube.com/iframe_api), in v1.0.0  now, only one request is made to load the script for all the videos.  the 'base.js' script is loaded within the youtube iframe . because every video is a iframe, it will load these script every time, nothing i can do to prevent that....

**Comment by lmartins** [comment]
Ah ok, thanks for clearing that out @supr3m0 
I think it's safe to close this then, right?
